package net.mcreator.whatisstone.init;

import net.mcreator.whatisstone.block.AnthraciteBlock;
import net.mcreator.whatisstone.block.ArkosicSandstoneBlock;
import net.mcreator.whatisstone.block.ArkosicSandstoneSlabBlock;
import net.mcreator.whatisstone.block.ArkosicSandstoneStairsBlock;
import net.mcreator.whatisstone.block.BlackMarbleBlock;
import net.mcreator.whatisstone.block.BlackMarbleSlabBlock;
import net.mcreator.whatisstone.block.BlackMarbleStairsBlock;
import net.mcreator.whatisstone.block.BrecciaBlock;
import net.mcreator.whatisstone.block.BrecciaSlabBlock;
import net.mcreator.whatisstone.block.BrecciaStairsBlock;
import net.mcreator.whatisstone.block.ConglomerateBlock;
import net.mcreator.whatisstone.block.ConglomerateSlabBlock;
import net.mcreator.whatisstone.block.ConglomerateStairsBlock;
import net.mcreator.whatisstone.block.DaciteBlock;
import net.mcreator.whatisstone.block.DaciteBrickSlabBlock;
import net.mcreator.whatisstone.block.DaciteBrickStairsBlock;
import net.mcreator.whatisstone.block.DaciteBricksBlock;
import net.mcreator.whatisstone.block.DaciteSlabBlock;
import net.mcreator.whatisstone.block.DaciteStairsBlock;
import net.mcreator.whatisstone.block.DolomiteBlock;
import net.mcreator.whatisstone.block.DolomiteSlabBlock;
import net.mcreator.whatisstone.block.DolomiteStairsBlock;
import net.mcreator.whatisstone.block.GabbroBlock;
import net.mcreator.whatisstone.block.GabbroSlabBlock;
import net.mcreator.whatisstone.block.GabbroStairsBlock;
import net.mcreator.whatisstone.block.GneissBlock;
import net.mcreator.whatisstone.block.GneissSlabBlock;
import net.mcreator.whatisstone.block.GneissStairsBlock;
import net.mcreator.whatisstone.block.GreyLimestoneBlock;
import net.mcreator.whatisstone.block.GreyLimestoneSlabBlock;
import net.mcreator.whatisstone.block.GreyLimestoneStairsBlock;
import net.mcreator.whatisstone.block.LimestoneBlock;
import net.mcreator.whatisstone.block.LimestoneBrickSlabBlock;
import net.mcreator.whatisstone.block.LimestoneBrickStairsBlock;
import net.mcreator.whatisstone.block.LimestoneBricksBlock;
import net.mcreator.whatisstone.block.LimestoneSlabBlock;
import net.mcreator.whatisstone.block.LimestoneStairsBlock;
import net.mcreator.whatisstone.block.MarbleBlock;
import net.mcreator.whatisstone.block.MarbleSlabBlock;
import net.mcreator.whatisstone.block.MarbleStairsBlock;
import net.mcreator.whatisstone.block.MudstoneBlock;
import net.mcreator.whatisstone.block.MudstoneSlabBlock;
import net.mcreator.whatisstone.block.MudstoneStairsBlock;
import net.mcreator.whatisstone.block.PegmatiteBlock;
import net.mcreator.whatisstone.block.PegmatiteSlabBlock;
import net.mcreator.whatisstone.block.PegmatiteStairsBlock;
import net.mcreator.whatisstone.block.PeridotiteBlock;
import net.mcreator.whatisstone.block.PeridotiteSlabBlock;
import net.mcreator.whatisstone.block.PeridotiteStairsBlock;
import net.mcreator.whatisstone.block.PolishedBlackMarbleBlock;
import net.mcreator.whatisstone.block.PolishedBlackMarbleSlabBlock;
import net.mcreator.whatisstone.block.PolishedBlackMarbleStairsBlock;
import net.mcreator.whatisstone.block.PolishedDolomiteBlock;
import net.mcreator.whatisstone.block.PolishedDolomiteSlabBlock;
import net.mcreator.whatisstone.block.PolishedDolomiteStairsBlock;
import net.mcreator.whatisstone.block.PolishedGneissBlock;
import net.mcreator.whatisstone.block.PolishedGneissSlabBlock;
import net.mcreator.whatisstone.block.PolishedGneissStairsBlock;
import net.mcreator.whatisstone.block.PolishedGreyLimestoneBlock;
import net.mcreator.whatisstone.block.PolishedGreyLimestoneSlabBlock;
import net.mcreator.whatisstone.block.PolishedGreyLimestoneStairsBlock;
import net.mcreator.whatisstone.block.PolishedLimestoneBlock;
import net.mcreator.whatisstone.block.PolishedLimestoneSlabBlock;
import net.mcreator.whatisstone.block.PolishedLimestoneStairsBlock;
import net.mcreator.whatisstone.block.PolishedMarbleBlock;
import net.mcreator.whatisstone.block.PolishedMarbleBrickSlabBlock;
import net.mcreator.whatisstone.block.PolishedMarbleBrickStairsBlock;
import net.mcreator.whatisstone.block.PolishedMarbleBricksBlock;
import net.mcreator.whatisstone.block.PolishedMarbleSlabBlock;
import net.mcreator.whatisstone.block.PolishedMarbleStairsBlock;
import net.mcreator.whatisstone.block.PolishedMudstoneBlock;
import net.mcreator.whatisstone.block.PolishedMudstoneSlabBlock;
import net.mcreator.whatisstone.block.PolishedMudstoneStairsBlock;
import net.mcreator.whatisstone.block.PolishedPeridotiteBlock;
import net.mcreator.whatisstone.block.PolishedPeridotiteSlabBlock;
import net.mcreator.whatisstone.block.PolishedPeridotiteStairsBlock;
import net.mcreator.whatisstone.block.PolishedQuartziteBlock;
import net.mcreator.whatisstone.block.PolishedQuartziteSlabBlock;
import net.mcreator.whatisstone.block.PolishedQuartziteStairsBlock;
import net.mcreator.whatisstone.block.PolishedRhyoliteBlock;
import net.mcreator.whatisstone.block.PolishedRhyoliteSlabBlock;
import net.mcreator.whatisstone.block.PolishedRhyoliteStairsBlock;
import net.mcreator.whatisstone.block.PolishedSchistBlock;
import net.mcreator.whatisstone.block.PolishedSerpentiniteBlock;
import net.mcreator.whatisstone.block.PolishedSerpentiniteSlabBlock;
import net.mcreator.whatisstone.block.PolishedSerpentiniteStairsBlock;
import net.mcreator.whatisstone.block.PolishedSoapstoneBlock;
import net.mcreator.whatisstone.block.PolishedSoapstoneSlabBlock;
import net.mcreator.whatisstone.block.PolishedSoapstoneStairsBlock;
import net.mcreator.whatisstone.block.PolishedWhiteLimestoneBlock;
import net.mcreator.whatisstone.block.PolishedWhiteLimestoneSlabBlock;
import net.mcreator.whatisstone.block.PolishedWhiteLimestoneStairsBlock;
import net.mcreator.whatisstone.block.PumiceBlock;
import net.mcreator.whatisstone.block.PumiceBrickSlabBlock;
import net.mcreator.whatisstone.block.PumiceBrickStairsBlock;
import net.mcreator.whatisstone.block.PumiceBricksBlock;
import net.mcreator.whatisstone.block.PumiceSlabBlock;
import net.mcreator.whatisstone.block.PumiceStairsBlock;
import net.mcreator.whatisstone.block.QuartziteBlock;
import net.mcreator.whatisstone.block.QuartziteSlabBlock;
import net.mcreator.whatisstone.block.QuartziteStairsBlock;
import net.mcreator.whatisstone.block.RhyoliteBlock;
import net.mcreator.whatisstone.block.RhyoliteSlabBlock;
import net.mcreator.whatisstone.block.RhyoliteStairsBlock;
import net.mcreator.whatisstone.block.SchistBlock;
import net.mcreator.whatisstone.block.SchistSlabBlock;
import net.mcreator.whatisstone.block.SchistStairsBlock;
import net.mcreator.whatisstone.block.ScoriaBlock;
import net.mcreator.whatisstone.block.ScoriaSlabBlock;
import net.mcreator.whatisstone.block.ScoriaStairsBlock;
import net.mcreator.whatisstone.block.SerpentiniteBlock;
import net.mcreator.whatisstone.block.SerpentiniteSlabBlock;
import net.mcreator.whatisstone.block.SerpentiniteStairsBlock;
import net.mcreator.whatisstone.block.ShaleBlock;
import net.mcreator.whatisstone.block.ShaleSlabBlock;
import net.mcreator.whatisstone.block.ShaleStairsBlock;
import net.mcreator.whatisstone.block.SlateBlock;
import net.mcreator.whatisstone.block.SlateSlabBlock;
import net.mcreator.whatisstone.block.SlateStairsBlock;
import net.mcreator.whatisstone.block.SoapstoneBlock;
import net.mcreator.whatisstone.block.SoapstoneSlabBlock;
import net.mcreator.whatisstone.block.SoapstoneStairsBlock;
import net.mcreator.whatisstone.block.WhiteGraniteBlock;
import net.mcreator.whatisstone.block.WhiteGraniteSlabBlock;
import net.mcreator.whatisstone.block.WhiteGraniteStairsBlock;
import net.mcreator.whatisstone.block.WhiteLimestoneBlock;
import net.mcreator.whatisstone.block.WhiteLimestoneSlabBlock;
import net.mcreator.whatisstone.block.WhiteLimestoneStairsBlock;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.Registries;
import net.minecraft.world.level.block.Block;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

public class WhatIsStoneModBlocks {
   public static DeferredRegister<Block> REGISTRY = DeferredRegister.createBlocks("what_is_stone");
   public static final DeferredHolder<Block, Block> PUMICE_BRICKS = REGISTRY.register("pumice_bricks", () -> new PumiceBricksBlock());
   public static final DeferredHolder<Block, Block> PUMICE = REGISTRY.register("pumice", () -> new PumiceBlock());
   public static final DeferredHolder<Block, Block> GNEISS = REGISTRY.register("gneiss", () -> new GneissBlock());
   public static final DeferredHolder<Block, Block> POLISHED_GNEISS = REGISTRY.register("polished_gneiss", () -> new PolishedGneissBlock());
   public static final DeferredHolder<Block, Block> MARBLE = REGISTRY.register("marble", () -> new MarbleBlock());
   public static final DeferredHolder<Block, Block> CONGLOMERATE = REGISTRY.register("conglomerate", () -> new ConglomerateBlock());
   public static final DeferredHolder<Block, Block> DACITE = REGISTRY.register("dacite", () -> new DaciteBlock());
   public static final DeferredHolder<Block, Block> GABBRO = REGISTRY.register("gabbro", () -> new GabbroBlock());
   public static final DeferredHolder<Block, Block> LIMESTONE = REGISTRY.register("limestone", () -> new LimestoneBlock());
   public static final DeferredHolder<Block, Block> BRECCIA = REGISTRY.register("breccia", () -> new BrecciaBlock());
   public static final DeferredHolder<Block, Block> WHITE_GRANITE = REGISTRY.register("white_granite", () -> new WhiteGraniteBlock());
   public static final DeferredHolder<Block, Block> DOLOMITE = REGISTRY.register("dolomite", () -> new DolomiteBlock());
   public static final DeferredHolder<Block, Block> RHYOLITE = REGISTRY.register("rhyolite", () -> new RhyoliteBlock());
   public static final DeferredHolder<Block, Block> SHALE = REGISTRY.register("shale", () -> new ShaleBlock());
   public static final DeferredHolder<Block, Block> PEGMATITE = REGISTRY.register("pegmatite", () -> new PegmatiteBlock());
   public static final DeferredHolder<Block, Block> SLATE = REGISTRY.register("slate", () -> new SlateBlock());
   public static final DeferredHolder<Block, Block> WHITE_LIMESTONE = REGISTRY.register("white_limestone", () -> new WhiteLimestoneBlock());
   public static final DeferredHolder<Block, Block> SCHIST = REGISTRY.register("schist", () -> new SchistBlock());
   public static final DeferredHolder<Block, Block> SCORIA = REGISTRY.register("scoria", () -> new ScoriaBlock());
   public static final DeferredHolder<Block, Block> BLACK_MARBLE = REGISTRY.register("black_marble", () -> new BlackMarbleBlock());
   public static final DeferredHolder<Block, Block> SERPENTINITE = REGISTRY.register("serpentinite", () -> new SerpentiniteBlock());
   public static final DeferredHolder<Block, Block> ANTHRACITE = REGISTRY.register("anthracite", () -> new AnthraciteBlock());
   public static final DeferredHolder<Block, Block> SOAPSTONE = REGISTRY.register("soapstone", () -> new SoapstoneBlock());
   public static final DeferredHolder<Block, Block> ARKOSIC_SANDSTONE = REGISTRY.register("arkosic_sandstone", () -> new ArkosicSandstoneBlock());
   public static final DeferredHolder<Block, Block> MUDSTONE = REGISTRY.register("mudstone", () -> new MudstoneBlock());
   public static final DeferredHolder<Block, Block> PERIDOTITE = REGISTRY.register("peridotite", () -> new PeridotiteBlock());
   public static final DeferredHolder<Block, Block> POLISHED_BLACK_MARBLE = REGISTRY.register("polished_black_marble", () -> new PolishedBlackMarbleBlock());
   public static final DeferredHolder<Block, Block> GREY_LIMESTONE = REGISTRY.register("grey_limestone", () -> new GreyLimestoneBlock());
   public static final DeferredHolder<Block, Block> POLISHED_MARBLE = REGISTRY.register("polished_marble", () -> new PolishedMarbleBlock());
   public static final DeferredHolder<Block, Block> POLISHED_MARBLE_BRICKS = REGISTRY.register("polished_marble_bricks", () -> new PolishedMarbleBricksBlock());
   public static final DeferredHolder<Block, Block> MARBLE_SLAB = REGISTRY.register("marble_slab", () -> new MarbleSlabBlock());
   public static final DeferredHolder<Block, Block> MARBLE_STAIRS = REGISTRY.register("marble_stairs", () -> new MarbleStairsBlock());
   public static final DeferredHolder<Block, Block> BLACK_MARBLE_SLAB = REGISTRY.register("black_marble_slab", () -> new BlackMarbleSlabBlock());
   public static final DeferredHolder<Block, Block> BLACK_MARBLE_STAIRS = REGISTRY.register("black_marble_stairs", () -> new BlackMarbleStairsBlock());
   public static final DeferredHolder<Block, Block> PUMICE_SLAB = REGISTRY.register("pumice_slab", () -> new PumiceSlabBlock());
   public static final DeferredHolder<Block, Block> PUMICE_STAIRS = REGISTRY.register("pumice_stairs", () -> new PumiceStairsBlock());
   public static final DeferredHolder<Block, Block> LIMESTONE_SLAB = REGISTRY.register("limestone_slab", () -> new LimestoneSlabBlock());
   public static final DeferredHolder<Block, Block> LIMESTONE_STAIRS = REGISTRY.register("limestone_stairs", () -> new LimestoneStairsBlock());
   public static final DeferredHolder<Block, Block> LIMESTONE_BRICKS = REGISTRY.register("limestone_bricks", () -> new LimestoneBricksBlock());
   public static final DeferredHolder<Block, Block> LIMESTONE_BRICK_SLAB = REGISTRY.register("limestone_brick_slab", () -> new LimestoneBrickSlabBlock());
   public static final DeferredHolder<Block, Block> LIMESTONE_BRICK_STAIRS = REGISTRY.register("limestone_brick_stairs", () -> new LimestoneBrickStairsBlock());
   public static final DeferredHolder<Block, Block> GNEISS_SLAB = REGISTRY.register("gneiss_slab", () -> new GneissSlabBlock());
   public static final DeferredHolder<Block, Block> GNEISS_STAIRS = REGISTRY.register("gneiss_stairs", () -> new GneissStairsBlock());
   public static final DeferredHolder<Block, Block> CONGLOMERATE_SLAB = REGISTRY.register("conglomerate_slab", () -> new ConglomerateSlabBlock());
   public static final DeferredHolder<Block, Block> CONGLOMERATE_STAIRS = REGISTRY.register("conglomerate_stairs", () -> new ConglomerateStairsBlock());
   public static final DeferredHolder<Block, Block> DACITE_SLAB = REGISTRY.register("dacite_slab", () -> new DaciteSlabBlock());
   public static final DeferredHolder<Block, Block> DACITE_STAIRS = REGISTRY.register("dacite_stairs", () -> new DaciteStairsBlock());
   public static final DeferredHolder<Block, Block> GABBRO_SLAB = REGISTRY.register("gabbro_slab", () -> new GabbroSlabBlock());
   public static final DeferredHolder<Block, Block> GABBRO_STAIRS = REGISTRY.register("gabbro_stairs", () -> new GabbroStairsBlock());
   public static final DeferredHolder<Block, Block> BRECCIA_SLAB = REGISTRY.register("breccia_slab", () -> new BrecciaSlabBlock());
   public static final DeferredHolder<Block, Block> BRECCIA_STAIRS = REGISTRY.register("breccia_stairs", () -> new BrecciaStairsBlock());
   public static final DeferredHolder<Block, Block> WHITE_GRANITE_SLAB = REGISTRY.register("white_granite_slab", () -> new WhiteGraniteSlabBlock());
   public static final DeferredHolder<Block, Block> WHITE_GRANITE_STAIRS = REGISTRY.register("white_granite_stairs", () -> new WhiteGraniteStairsBlock());
   public static final DeferredHolder<Block, Block> DOLOMITE_SLAB = REGISTRY.register("dolomite_slab", () -> new DolomiteSlabBlock());
   public static final DeferredHolder<Block, Block> DOLOMITE_STAIRS = REGISTRY.register("dolomite_stairs", () -> new DolomiteStairsBlock());
   public static final DeferredHolder<Block, Block> RHYOLITE_SLAB = REGISTRY.register("rhyolite_slab", () -> new RhyoliteSlabBlock());
   public static final DeferredHolder<Block, Block> RHYOLITE_STAIRS = REGISTRY.register("rhyolite_stairs", () -> new RhyoliteStairsBlock());
   public static final DeferredHolder<Block, Block> SHALE_SLAB = REGISTRY.register("shale_slab", () -> new ShaleSlabBlock());
   public static final DeferredHolder<Block, Block> SHALE_STAIRS = REGISTRY.register("shale_stairs", () -> new ShaleStairsBlock());
   public static final DeferredHolder<Block, Block> PEGMATITE_SLAB = REGISTRY.register("pegmatite_slab", () -> new PegmatiteSlabBlock());
   public static final DeferredHolder<Block, Block> PEGMATITE_STAIRS = REGISTRY.register("pegmatite_stairs", () -> new PegmatiteStairsBlock());
   public static final DeferredHolder<Block, Block> SLATE_SLAB = REGISTRY.register("slate_slab", () -> new SlateSlabBlock());
   public static final DeferredHolder<Block, Block> SLATE_STAIRS = REGISTRY.register("slate_stairs", () -> new SlateStairsBlock());
   public static final DeferredHolder<Block, Block> WHITE_LIMESTONE_SLAB = REGISTRY.register("white_limestone_slab", () -> new WhiteLimestoneSlabBlock());
   public static final DeferredHolder<Block, Block> WHITE_LIMESTONE_STAIRS = REGISTRY.register("white_limestone_stairs", () -> new WhiteLimestoneStairsBlock());
   public static final DeferredHolder<Block, Block> SCHIST_SLAB = REGISTRY.register("schist_slab", () -> new SchistSlabBlock());
   public static final DeferredHolder<Block, Block> SCHIST_STAIRS = REGISTRY.register("schist_stairs", () -> new SchistStairsBlock());
   public static final DeferredHolder<Block, Block> SCORIA_SLAB = REGISTRY.register("scoria_slab", () -> new ScoriaSlabBlock());
   public static final DeferredHolder<Block, Block> SCORIA_STAIRS = REGISTRY.register("scoria_stairs", () -> new ScoriaStairsBlock());
   public static final DeferredHolder<Block, Block> SERPENTINITE_SLAB = REGISTRY.register("serpentinite_slab", () -> new SerpentiniteSlabBlock());
   public static final DeferredHolder<Block, Block> SERPENTINITE_STAIRS = REGISTRY.register("serpentinite_stairs", () -> new SerpentiniteStairsBlock());
   public static final DeferredHolder<Block, Block> SOAPSTONE_SLAB = REGISTRY.register("soapstone_slab", () -> new SoapstoneSlabBlock());
   public static final DeferredHolder<Block, Block> SOAPSTONE_STAIRS = REGISTRY.register("soapstone_stairs", () -> new SoapstoneStairsBlock());
   public static final DeferredHolder<Block, Block> ARKOSIC_SANDSTONE_SLAB = REGISTRY.register("arkosic_sandstone_slab", () -> new ArkosicSandstoneSlabBlock());
   public static final DeferredHolder<Block, Block> ARKOSIC_SANDSTONE_STAIRS = REGISTRY.register("arkosic_sandstone_stairs", () -> new ArkosicSandstoneStairsBlock());
   public static final DeferredHolder<Block, Block> MUDSTONE_SLAB = REGISTRY.register("mudstone_slab", () -> new MudstoneSlabBlock());
   public static final DeferredHolder<Block, Block> MUDSTONE_STAIRS = REGISTRY.register("mudstone_stairs", () -> new MudstoneStairsBlock());
   public static final DeferredHolder<Block, Block> PERIDOTITE_SLAB = REGISTRY.register("peridotite_slab", () -> new PeridotiteSlabBlock());
   public static final DeferredHolder<Block, Block> PERIDOTITE_STAIRS = REGISTRY.register("peridotite_stairs", () -> new PeridotiteStairsBlock());
   public static final DeferredHolder<Block, Block> GREY_LIMESTONE_SLAB = REGISTRY.register("grey_limestone_slab", () -> new GreyLimestoneSlabBlock());
   public static final DeferredHolder<Block, Block> GREY_LIMESTONE_STAIRS = REGISTRY.register("grey_limestone_stairs", () -> new GreyLimestoneStairsBlock());
   public static final DeferredHolder<Block, Block> PUMICE_BRICK_SLAB = REGISTRY.register("pumice_brick_slab", () -> new PumiceBrickSlabBlock());
   public static final DeferredHolder<Block, Block> PUMICE_BRICK_STAIRS = REGISTRY.register("pumice_brick_stairs", () -> new PumiceBrickStairsBlock());
   public static final DeferredHolder<Block, Block> POLISHED_MARBLE_BRICK_SLAB = REGISTRY.register("polished_marble_brick_slab", () -> new PolishedMarbleBrickSlabBlock());
   public static final DeferredHolder<Block, Block> POLISHED_MARBLE_BRICK_STAIRS = REGISTRY.register("polished_marble_brick_stairs", () -> new PolishedMarbleBrickStairsBlock());
   public static final DeferredHolder<Block, Block> QUARTZITE = REGISTRY.register("quartzite", () -> new QuartziteBlock());
   public static final DeferredHolder<Block, Block> QUARTZITE_SLAB = REGISTRY.register("quartzite_slab", () -> new QuartziteSlabBlock());
   public static final DeferredHolder<Block, Block> QUARTZITE_STAIRS = REGISTRY.register("quartzite_stairs", () -> new QuartziteStairsBlock());
   public static final DeferredHolder<Block, Block> DACITE_BRICKS = REGISTRY.register("dacite_bricks", () -> new DaciteBricksBlock());
   public static final DeferredHolder<Block, Block> DACITE_BRICK_SLAB = REGISTRY.register("dacite_brick_slab", () -> new DaciteBrickSlabBlock());
   public static final DeferredHolder<Block, Block> DACITE_BRICK_STAIRS = REGISTRY.register("dacite_brick_stairs", () -> new DaciteBrickStairsBlock());
   public static final DeferredHolder<Block, Block> POLISHED_SOAPSTONE = REGISTRY.register("polished_soapstone", () -> new PolishedSoapstoneBlock());
   public static final DeferredHolder<Block, Block> POLISHED_SERPENTINITE = REGISTRY.register("polished_serpentinite", () -> new PolishedSerpentiniteBlock());
   public static final DeferredHolder<Block, Block> POLISHED_DOLOMITE = REGISTRY.register("polished_dolomite", () -> new PolishedDolomiteBlock());
   public static final DeferredHolder<Block, Block> POLISHED_SOAPSTONE_SLAB = REGISTRY.register("polished_soapstone_slab", () -> new PolishedSoapstoneSlabBlock());
   public static final DeferredHolder<Block, Block> POLISHED_DOLOMITE_SLAB = REGISTRY.register("polished_dolomite_slab", () -> new PolishedDolomiteSlabBlock());
   public static final DeferredHolder<Block, Block> POLISHED_SERPENTINITE_SLAB = REGISTRY.register("polished_serpentinite_slab", () -> new PolishedSerpentiniteSlabBlock());
   public static final DeferredHolder<Block, Block> POLISHED_MARBLE_SLAB = REGISTRY.register("polished_marble_slab", () -> new PolishedMarbleSlabBlock());
   public static final DeferredHolder<Block, Block> POLISHED_MUDSTONE = REGISTRY.register("polished_mudstone", () -> new PolishedMudstoneBlock());
   public static final DeferredHolder<Block, Block> POLISHED_GREY_LIMESTONE = REGISTRY.register("polished_grey_limestone", () -> new PolishedGreyLimestoneBlock());
   public static final DeferredHolder<Block, Block> POLISHED_RHYOLITE = REGISTRY.register("polished_rhyolite", () -> new PolishedRhyoliteBlock());
   public static final DeferredHolder<Block, Block> POLISHED_QUARTZITE = REGISTRY.register("polished_quartzite", () -> new PolishedQuartziteBlock());
   public static final DeferredHolder<Block, Block> POLISHED_PERIDOTITE = REGISTRY.register("polished_peridotite", () -> new PolishedPeridotiteBlock());
   public static final DeferredHolder<Block, Block> POLISHED_LIMESTONE = REGISTRY.register("polished_limestone", () -> new PolishedLimestoneBlock());
   public static final DeferredHolder<Block, Block> POLISHED_MARBLE_STAIRS = REGISTRY.register("polished_marble_stairs", () -> new PolishedMarbleStairsBlock());
   public static final DeferredHolder<Block, Block> POLISHED_SOAPSTONE_STAIRS = REGISTRY.register("polished_soapstone_stairs", () -> new PolishedSoapstoneStairsBlock());
   public static final DeferredHolder<Block, Block> POLISHED_DOLOMITE_STAIRS = REGISTRY.register("polished_dolomite_stairs", () -> new PolishedDolomiteStairsBlock());
   public static final DeferredHolder<Block, Block> POLISHED_SERPENTINITE_STAIRS = REGISTRY.register("polished_serpentinite_stairs", () -> new PolishedSerpentiniteStairsBlock());
   public static final DeferredHolder<Block, Block> POLISHED_MUDSTONE_SLAB = REGISTRY.register("polished_mudstone_slab", () -> new PolishedMudstoneSlabBlock());
   public static final DeferredHolder<Block, Block> POLISHED_MUDSTONE_STAIRS = REGISTRY.register("polished_mudstone_stairs", () -> new PolishedMudstoneStairsBlock());
   public static final DeferredHolder<Block, Block> POLISHED_GREY_LIMESTONE_SLAB = REGISTRY.register("polished_grey_limestone_slab", () -> new PolishedGreyLimestoneSlabBlock());
   public static final DeferredHolder<Block, Block> POLISHED_GREY_LIMESTONE_STAIRS = REGISTRY.register("polished_grey_limestone_stairs", () -> new PolishedGreyLimestoneStairsBlock());
   public static final DeferredHolder<Block, Block> POLISHED_RHYOLITE_SLAB = REGISTRY.register("polished_rhyolite_slab", () -> new PolishedRhyoliteSlabBlock());
   public static final DeferredHolder<Block, Block> POLISHED_RHYOLITE_STAIRS = REGISTRY.register("polished_rhyolite_stairs", () -> new PolishedRhyoliteStairsBlock());
   public static final DeferredHolder<Block, Block> POLISHED_QUARTZITE_SLAB = REGISTRY.register("polished_quartzite_slab", () -> new PolishedQuartziteSlabBlock());
   public static final DeferredHolder<Block, Block> POLISHED_QUARTZITE_STAIRS = REGISTRY.register("polished_quartzite_stairs", () -> new PolishedQuartziteStairsBlock());
   public static final DeferredHolder<Block, Block> POLISHED_PERIDOTITE_SLAB = REGISTRY.register("polished_peridotite_slab", () -> new PolishedPeridotiteSlabBlock());
   public static final DeferredHolder<Block, Block> POLISHED_PERIDOTITE_STAIRS = REGISTRY.register("polished_peridotite_stairs", () -> new PolishedPeridotiteStairsBlock());
   public static final DeferredHolder<Block, Block> POLISHED_LIMESTONE_SLAB = REGISTRY.register("polished_limestone_slab", () -> new PolishedLimestoneSlabBlock());
   public static final DeferredHolder<Block, Block> POLISHED_LIMESTONE_STAIRS = REGISTRY.register("polished_limestone_stairs", () -> new PolishedLimestoneStairsBlock());
   public static final DeferredHolder<Block, Block> POLISHED_GNEISS_SLAB = REGISTRY.register("polished_gneiss_slab", () -> new PolishedGneissSlabBlock());
   public static final DeferredHolder<Block, Block> POLISHED_GNEISS_STAIRS = REGISTRY.register("polished_gneiss_stairs", () -> new PolishedGneissStairsBlock());
   public static final DeferredHolder<Block, Block> POLISHED_BLACK_MARBLE_SLAB = REGISTRY.register("polished_black_marble_slab", () -> new PolishedBlackMarbleSlabBlock());
   public static final DeferredHolder<Block, Block> POLISHED_BLACK_MARBLE_STAIRS = REGISTRY.register("polished_black_marble_stairs", () -> new PolishedBlackMarbleStairsBlock());
   public static final DeferredHolder<Block, Block> POLISHED_SCHIST = REGISTRY.register("polished_schist", () -> new PolishedSchistBlock());
   public static final DeferredHolder<Block, Block> POLISHED_WHITE_LIMESTONE = REGISTRY.register("polished_white_limestone", () -> new PolishedWhiteLimestoneBlock());
   public static final DeferredHolder<Block, Block> POLISHED_WHITE_LIMESTONE_SLAB = REGISTRY.register("polished_white_limestone_slab", () -> new PolishedWhiteLimestoneSlabBlock());
   public static final DeferredHolder<Block, Block> POLISHED_WHITE_LIMESTONE_STAIRS = REGISTRY.register("polished_white_limestone_stairs", () -> new PolishedWhiteLimestoneStairsBlock());

}
