modLoader="javafml"
loaderVersion="[2,)"
license="Academic Free License v3.0"

[[mods]]
modId="what_is_stone"
version="0.1"
displayName="What is 'Stone'? (Colorful Caves)"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Numerosity, MCreator"
description="Okay, but really what is 'Stone'? What kind of stone? Let's add a bit of spice to the existing caves, vanilla style!"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.what_is_stone]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"



