package me.psiber.thisisstone.init;

import me.psiber.thisisstone.item.ChunkOfAnthraciteItem;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

public class ThisIsStoneModItems {
   public static final DeferredRegister<Item> REGISTRY;
   public static final DeferredHolder<Item, Item> PUMICE_BRICKS;
   public static final DeferredHolder<Item, Item> PUMICE;
   public static final DeferredHolder<Item, Item> GNEISS;
   public static final DeferredHolder<Item, Item> POLISHED_GNEISS;
   public static final DeferredHolder<Item, Item> MARBLE;
   public static final DeferredHolder<Item, Item> CONGLOMERATE;
   public static final DeferredHolder<Item, Item> DACITE;
   public static final DeferredHolder<Item, Item> GABBRO;
   public static final DeferredHolder<Item, Item> LIMESTONE;
   public static final DeferredHolder<Item, Item> BRECCIA;
   public static final DeferredHolder<Item, Item> WHITE_GRANITE;
   public static final DeferredHolder<Item, Item> DOLOMITE;
   public static final DeferredHolder<Item, Item> RHYOLITE;
   public static final DeferredHolder<Item, Item> SHALE;
   public static final DeferredHolder<Item, Item> PEGMATITE;
   public static final DeferredHolder<Item, Item> SLATE;
   public static final DeferredHolder<Item, Item> WHITE_LIMESTONE;
   public static final DeferredHolder<Item, Item> SCHIST;
   public static final DeferredHolder<Item, Item> SCORIA;
   public static final DeferredHolder<Item, Item> BLACK_MARBLE;
   public static final DeferredHolder<Item, Item> SERPENTINITE;
   public static final DeferredHolder<Item, Item> ANTHRACITE;
   public static final DeferredHolder<Item, Item> CHUNK_OF_ANTHRACITE;
   public static final DeferredHolder<Item, Item> SOAPSTONE;
   public static final DeferredHolder<Item, Item> ARKOSIC_SANDSTONE;
   public static final DeferredHolder<Item, Item> MUDSTONE;
   public static final DeferredHolder<Item, Item> PERIDOTITE;
   public static final DeferredHolder<Item, Item> POLISHED_BLACK_MARBLE;
   public static final DeferredHolder<Item, Item> GREY_LIMESTONE;
   public static final DeferredHolder<Item, Item> POLISHED_MARBLE;
   public static final DeferredHolder<Item, Item> POLISHED_MARBLE_BRICKS;
   public static final DeferredHolder<Item, Item> MARBLE_SLAB;
   public static final DeferredHolder<Item, Item> MARBLE_STAIRS;
   public static final DeferredHolder<Item, Item> BLACK_MARBLE_SLAB;
   public static final DeferredHolder<Item, Item> BLACK_MARBLE_STAIRS;
   public static final DeferredHolder<Item, Item> PUMICE_SLAB;
   public static final DeferredHolder<Item, Item> PUMICE_STAIRS;
   public static final DeferredHolder<Item, Item> LIMESTONE_SLAB;
   public static final DeferredHolder<Item, Item> LIMESTONE_STAIRS;
   public static final DeferredHolder<Item, Item> LIMESTONE_BRICKS;
   public static final DeferredHolder<Item, Item> LIMESTONE_BRICK_SLAB;
   public static final DeferredHolder<Item, Item> LIMESTONE_BRICK_STAIRS;
   public static final DeferredHolder<Item, Item> GNEISS_SLAB;
   public static final DeferredHolder<Item, Item> GNEISS_STAIRS;
   public static final DeferredHolder<Item, Item> CONGLOMERATE_SLAB;
   public static final DeferredHolder<Item, Item> CONGLOMERATE_STAIRS;
   public static final DeferredHolder<Item, Item> DACITE_SLAB;
   public static final DeferredHolder<Item, Item> DACITE_STAIRS;
   public static final DeferredHolder<Item, Item> GABBRO_SLAB;
   public static final DeferredHolder<Item, Item> GABBRO_STAIRS;
   public static final DeferredHolder<Item, Item> BRECCIA_SLAB;
   public static final DeferredHolder<Item, Item> BRECCIA_STAIRS;
   public static final DeferredHolder<Item, Item> WHITE_GRANITE_SLAB;
   public static final DeferredHolder<Item, Item> WHITE_GRANITE_STAIRS;
   public static final DeferredHolder<Item, Item> DOLOMITE_SLAB;
   public static final DeferredHolder<Item, Item> DOLOMITE_STAIRS;
   public static final DeferredHolder<Item, Item> RHYOLITE_SLAB;
   public static final DeferredHolder<Item, Item> RHYOLITE_STAIRS;
   public static final DeferredHolder<Item, Item> SHALE_SLAB;
   public static final DeferredHolder<Item, Item> SHALE_STAIRS;
   public static final DeferredHolder<Item, Item> PEGMATITE_SLAB;
   public static final DeferredHolder<Item, Item> PEGMATITE_STAIRS;
   public static final DeferredHolder<Item, Item> SLATE_SLAB;
   public static final DeferredHolder<Item, Item> SLATE_STAIRS;
   public static final DeferredHolder<Item, Item> WHITE_LIMESTONE_SLAB;
   public static final DeferredHolder<Item, Item> WHITE_LIMESTONE_STAIRS;
   public static final DeferredHolder<Item, Item> SCHIST_SLAB;
   public static final DeferredHolder<Item, Item> SCHIST_STAIRS;
   public static final DeferredHolder<Item, Item> SCORIA_SLAB;
   public static final DeferredHolder<Item, Item> SCORIA_STAIRS;
   public static final DeferredHolder<Item, Item> SERPENTINITE_SLAB;
   public static final DeferredHolder<Item, Item> SERPENTINITE_STAIRS;
   public static final DeferredHolder<Item, Item> SOAPSTONE_SLAB;
   public static final DeferredHolder<Item, Item> SOAPSTONE_STAIRS;
   public static final DeferredHolder<Item, Item> ARKOSIC_SANDSTONE_SLAB;
   public static final DeferredHolder<Item, Item> ARKOSIC_SANDSTONE_STAIRS;
   public static final DeferredHolder<Item, Item> MUDSTONE_SLAB;
   public static final DeferredHolder<Item, Item> MUDSTONE_STAIRS;
   public static final DeferredHolder<Item, Item> PERIDOTITE_SLAB;
   public static final DeferredHolder<Item, Item> PERIDOTITE_STAIRS;
   public static final DeferredHolder<Item, Item> GREY_LIMESTONE_SLAB;
   public static final DeferredHolder<Item, Item> GREY_LIMESTONE_STAIRS;
   public static final DeferredHolder<Item, Item> PUMICE_BRICK_SLAB;
   public static final DeferredHolder<Item, Item> PUMICE_BRICK_STAIRS;
   public static final DeferredHolder<Item, Item> POLISHED_MARBLE_BRICK_SLAB;
   public static final DeferredHolder<Item, Item> POLISHED_MARBLE_BRICK_STAIRS;
   public static final DeferredHolder<Item, Item> QUARTZITE;
   public static final DeferredHolder<Item, Item> QUARTZITE_SLAB;
   public static final DeferredHolder<Item, Item> QUARTZITE_STAIRS;
   public static final DeferredHolder<Item, Item> DACITE_BRICKS;
   public static final DeferredHolder<Item, Item> DACITE_BRICK_SLAB;
   public static final DeferredHolder<Item, Item> DACITE_BRICK_STAIRS;
   public static final DeferredHolder<Item, Item> POLISHED_SOAPSTONE;
   public static final DeferredHolder<Item, Item> POLISHED_SERPENTINITE;
   public static final DeferredHolder<Item, Item> POLISHED_DOLOMITE;
   public static final DeferredHolder<Item, Item> POLISHED_SOAPSTONE_SLAB;
   public static final DeferredHolder<Item, Item> POLISHED_DOLOMITE_SLAB;
   public static final DeferredHolder<Item, Item> POLISHED_SERPENTINITE_SLAB;
   public static final DeferredHolder<Item, Item> POLISHED_MARBLE_SLAB;
   public static final DeferredHolder<Item, Item> POLISHED_MUDSTONE;
   public static final DeferredHolder<Item, Item> POLISHED_GREY_LIMESTONE;
   public static final DeferredHolder<Item, Item> POLISHED_RHYOLITE;
   public static final DeferredHolder<Item, Item> POLISHED_QUARTZITE;
   public static final DeferredHolder<Item, Item> POLISHED_PERIDOTITE;
   public static final DeferredHolder<Item, Item> POLISHED_LIMESTONE;
   public static final DeferredHolder<Item, Item> POLISHED_MARBLE_STAIRS;
   public static final DeferredHolder<Item, Item> POLISHED_SOAPSTONE_STAIRS;
   public static final DeferredHolder<Item, Item> POLISHED_DOLOMITE_STAIRS;
   public static final DeferredHolder<Item, Item> POLISHED_SERPENTINITE_STAIRS;
   public static final DeferredHolder<Item, Item> POLISHED_MUDSTONE_SLAB;
   public static final DeferredHolder<Item, Item> POLISHED_MUDSTONE_STAIRS;
   public static final DeferredHolder<Item, Item> POLISHED_GREY_LIMESTONE_SLAB;
   public static final DeferredHolder<Item, Item> POLISHED_GREY_LIMESTONE_STAIRS;
   public static final DeferredHolder<Item, Item> POLISHED_RHYOLITE_SLAB;
   public static final DeferredHolder<Item, Item> POLISHED_RHYOLITE_STAIRS;
   public static final DeferredHolder<Item, Item> POLISHED_QUARTZITE_SLAB;
   public static final DeferredHolder<Item, Item> POLISHED_QUARTZITE_STAIRS;
   public static final DeferredHolder<Item, Item> POLISHED_PERIDOTITE_SLAB;
   public static final DeferredHolder<Item, Item> POLISHED_PERIDOTITE_STAIRS;
   public static final DeferredHolder<Item, Item> POLISHED_LIMESTONE_SLAB;
   public static final DeferredHolder<Item, Item> POLISHED_LIMESTONE_STAIRS;
   public static final DeferredHolder<Item, Item> POLISHED_GNEISS_SLAB;
   public static final DeferredHolder<Item, Item> POLISHED_GNEISS_STAIRS;
   public static final DeferredHolder<Item, Item> POLISHED_BLACK_MARBLE_SLAB;
   public static final DeferredHolder<Item, Item> POLISHED_BLACK_MARBLE_STAIRS;
   public static final DeferredHolder<Item, Item> POLISHED_SCHIST;
   public static final DeferredHolder<Item, Item> POLISHED_WHITE_LIMESTONE;
   public static final DeferredHolder<Item, Item> POLISHED_WHITE_LIMESTONE_SLAB;
   public static final DeferredHolder<Item, Item> POLISHED_WHITE_LIMESTONE_STAIRS;

   public static void register(IEventBus bus) {
      REGISTRY.register(bus);
   }

   private static DeferredHolder<Item, Item> block(DeferredHolder<Block, Block> block) {
      return REGISTRY.register(block.getId().getPath(), () -> {
         return new BlockItem((Block)block.get(), new Item.Properties());
      });
   }

   static {
      REGISTRY = DeferredRegister.create(BuiltInRegistries.ITEM, "this_is_stone");
      PUMICE_BRICKS = block(ThisIsStoneModBlocks.PUMICE_BRICKS);
      PUMICE = block(ThisIsStoneModBlocks.PUMICE);
      GNEISS = block(ThisIsStoneModBlocks.GNEISS);
      POLISHED_GNEISS = block(ThisIsStoneModBlocks.POLISHED_GNEISS);
      MARBLE = block(ThisIsStoneModBlocks.MARBLE);
      CONGLOMERATE = block(ThisIsStoneModBlocks.CONGLOMERATE);
      DACITE = block(ThisIsStoneModBlocks.DACITE);
      GABBRO = block(ThisIsStoneModBlocks.GABBRO);
      LIMESTONE = block(ThisIsStoneModBlocks.LIMESTONE);
      BRECCIA = block(ThisIsStoneModBlocks.BRECCIA);
      WHITE_GRANITE = block(ThisIsStoneModBlocks.WHITE_GRANITE);
      DOLOMITE = block(ThisIsStoneModBlocks.DOLOMITE);
      RHYOLITE = block(ThisIsStoneModBlocks.RHYOLITE);
      SHALE = block(ThisIsStoneModBlocks.SHALE);
      PEGMATITE = block(ThisIsStoneModBlocks.PEGMATITE);
      SLATE = block(ThisIsStoneModBlocks.SLATE);
      WHITE_LIMESTONE = block(ThisIsStoneModBlocks.WHITE_LIMESTONE);
      SCHIST = block(ThisIsStoneModBlocks.SCHIST);
      SCORIA = block(ThisIsStoneModBlocks.SCORIA);
      BLACK_MARBLE = block(ThisIsStoneModBlocks.BLACK_MARBLE);
      SERPENTINITE = block(ThisIsStoneModBlocks.SERPENTINITE);
      ANTHRACITE = block(ThisIsStoneModBlocks.ANTHRACITE);
      CHUNK_OF_ANTHRACITE = REGISTRY.register("chunk_of_anthracite", () -> {
         return new ChunkOfAnthraciteItem();
      });
      SOAPSTONE = block(ThisIsStoneModBlocks.SOAPSTONE);
      ARKOSIC_SANDSTONE = block(ThisIsStoneModBlocks.ARKOSIC_SANDSTONE);
      MUDSTONE = block(ThisIsStoneModBlocks.MUDSTONE);
      PERIDOTITE = block(ThisIsStoneModBlocks.PERIDOTITE);
      POLISHED_BLACK_MARBLE = block(ThisIsStoneModBlocks.POLISHED_BLACK_MARBLE);
      GREY_LIMESTONE = block(ThisIsStoneModBlocks.GREY_LIMESTONE);
      POLISHED_MARBLE = block(ThisIsStoneModBlocks.POLISHED_MARBLE);
      POLISHED_MARBLE_BRICKS = block(ThisIsStoneModBlocks.POLISHED_MARBLE_BRICKS);
      MARBLE_SLAB = block(ThisIsStoneModBlocks.MARBLE_SLAB);
      MARBLE_STAIRS = block(ThisIsStoneModBlocks.MARBLE_STAIRS);
      BLACK_MARBLE_SLAB = block(ThisIsStoneModBlocks.BLACK_MARBLE_SLAB);
      BLACK_MARBLE_STAIRS = block(ThisIsStoneModBlocks.BLACK_MARBLE_STAIRS);
      PUMICE_SLAB = block(ThisIsStoneModBlocks.PUMICE_SLAB);
      PUMICE_STAIRS = block(ThisIsStoneModBlocks.PUMICE_STAIRS);
      LIMESTONE_SLAB = block(ThisIsStoneModBlocks.LIMESTONE_SLAB);
      LIMESTONE_STAIRS = block(ThisIsStoneModBlocks.LIMESTONE_STAIRS);
      LIMESTONE_BRICKS = block(ThisIsStoneModBlocks.LIMESTONE_BRICKS);
      LIMESTONE_BRICK_SLAB = block(ThisIsStoneModBlocks.LIMESTONE_BRICK_SLAB);
      LIMESTONE_BRICK_STAIRS = block(ThisIsStoneModBlocks.LIMESTONE_BRICK_STAIRS);
      GNEISS_SLAB = block(ThisIsStoneModBlocks.GNEISS_SLAB);
      GNEISS_STAIRS = block(ThisIsStoneModBlocks.GNEISS_STAIRS);
      CONGLOMERATE_SLAB = block(ThisIsStoneModBlocks.CONGLOMERATE_SLAB);
      CONGLOMERATE_STAIRS = block(ThisIsStoneModBlocks.CONGLOMERATE_STAIRS);
      DACITE_SLAB = block(ThisIsStoneModBlocks.DACITE_SLAB);
      DACITE_STAIRS = block(ThisIsStoneModBlocks.DACITE_STAIRS);
      GABBRO_SLAB = block(ThisIsStoneModBlocks.GABBRO_SLAB);
      GABBRO_STAIRS = block(ThisIsStoneModBlocks.GABBRO_STAIRS);
      BRECCIA_SLAB = block(ThisIsStoneModBlocks.BRECCIA_SLAB);
      BRECCIA_STAIRS = block(ThisIsStoneModBlocks.BRECCIA_STAIRS);
      WHITE_GRANITE_SLAB = block(ThisIsStoneModBlocks.WHITE_GRANITE_SLAB);
      WHITE_GRANITE_STAIRS = block(ThisIsStoneModBlocks.WHITE_GRANITE_STAIRS);
      DOLOMITE_SLAB = block(ThisIsStoneModBlocks.DOLOMITE_SLAB);
      DOLOMITE_STAIRS = block(ThisIsStoneModBlocks.DOLOMITE_STAIRS);
      RHYOLITE_SLAB = block(ThisIsStoneModBlocks.RHYOLITE_SLAB);
      RHYOLITE_STAIRS = block(ThisIsStoneModBlocks.RHYOLITE_STAIRS);
      SHALE_SLAB = block(ThisIsStoneModBlocks.SHALE_SLAB);
      SHALE_STAIRS = block(ThisIsStoneModBlocks.SHALE_STAIRS);
      PEGMATITE_SLAB = block(ThisIsStoneModBlocks.PEGMATITE_SLAB);
      PEGMATITE_STAIRS = block(ThisIsStoneModBlocks.PEGMATITE_STAIRS);
      SLATE_SLAB = block(ThisIsStoneModBlocks.SLATE_SLAB);
      SLATE_STAIRS = block(ThisIsStoneModBlocks.SLATE_STAIRS);
      WHITE_LIMESTONE_SLAB = block(ThisIsStoneModBlocks.WHITE_LIMESTONE_SLAB);
      WHITE_LIMESTONE_STAIRS = block(ThisIsStoneModBlocks.WHITE_LIMESTONE_STAIRS);
      SCHIST_SLAB = block(ThisIsStoneModBlocks.SCHIST_SLAB);
      SCHIST_STAIRS = block(ThisIsStoneModBlocks.SCHIST_STAIRS);
      SCORIA_SLAB = block(ThisIsStoneModBlocks.SCORIA_SLAB);
      SCORIA_STAIRS = block(ThisIsStoneModBlocks.SCORIA_STAIRS);
      SERPENTINITE_SLAB = block(ThisIsStoneModBlocks.SERPENTINITE_SLAB);
      SERPENTINITE_STAIRS = block(ThisIsStoneModBlocks.SERPENTINITE_STAIRS);
      SOAPSTONE_SLAB = block(ThisIsStoneModBlocks.SOAPSTONE_SLAB);
      SOAPSTONE_STAIRS = block(ThisIsStoneModBlocks.SOAPSTONE_STAIRS);
      ARKOSIC_SANDSTONE_SLAB = block(ThisIsStoneModBlocks.ARKOSIC_SANDSTONE_SLAB);
      ARKOSIC_SANDSTONE_STAIRS = block(ThisIsStoneModBlocks.ARKOSIC_SANDSTONE_STAIRS);
      MUDSTONE_SLAB = block(ThisIsStoneModBlocks.MUDSTONE_SLAB);
      MUDSTONE_STAIRS = block(ThisIsStoneModBlocks.MUDSTONE_STAIRS);
      PERIDOTITE_SLAB = block(ThisIsStoneModBlocks.PERIDOTITE_SLAB);
      PERIDOTITE_STAIRS = block(ThisIsStoneModBlocks.PERIDOTITE_STAIRS);
      GREY_LIMESTONE_SLAB = block(ThisIsStoneModBlocks.GREY_LIMESTONE_SLAB);
      GREY_LIMESTONE_STAIRS = block(ThisIsStoneModBlocks.GREY_LIMESTONE_STAIRS);
      PUMICE_BRICK_SLAB = block(ThisIsStoneModBlocks.PUMICE_BRICK_SLAB);
      PUMICE_BRICK_STAIRS = block(ThisIsStoneModBlocks.PUMICE_BRICK_STAIRS);
      POLISHED_MARBLE_BRICK_SLAB = block(ThisIsStoneModBlocks.POLISHED_MARBLE_BRICK_SLAB);
      POLISHED_MARBLE_BRICK_STAIRS = block(ThisIsStoneModBlocks.POLISHED_MARBLE_BRICK_STAIRS);
      QUARTZITE = block(ThisIsStoneModBlocks.QUARTZITE);
      QUARTZITE_SLAB = block(ThisIsStoneModBlocks.QUARTZITE_SLAB);
      QUARTZITE_STAIRS = block(ThisIsStoneModBlocks.QUARTZITE_STAIRS);
      DACITE_BRICKS = block(ThisIsStoneModBlocks.DACITE_BRICKS);
      DACITE_BRICK_SLAB = block(ThisIsStoneModBlocks.DACITE_BRICK_SLAB);
      DACITE_BRICK_STAIRS = block(ThisIsStoneModBlocks.DACITE_BRICK_STAIRS);
      POLISHED_SOAPSTONE = block(ThisIsStoneModBlocks.POLISHED_SOAPSTONE);
      POLISHED_SERPENTINITE = block(ThisIsStoneModBlocks.POLISHED_SERPENTINITE);
      POLISHED_DOLOMITE = block(ThisIsStoneModBlocks.POLISHED_DOLOMITE);
      POLISHED_SOAPSTONE_SLAB = block(ThisIsStoneModBlocks.POLISHED_SOAPSTONE_SLAB);
      POLISHED_DOLOMITE_SLAB = block(ThisIsStoneModBlocks.POLISHED_DOLOMITE_SLAB);
      POLISHED_SERPENTINITE_SLAB = block(ThisIsStoneModBlocks.POLISHED_SERPENTINITE_SLAB);
      POLISHED_MARBLE_SLAB = block(ThisIsStoneModBlocks.POLISHED_MARBLE_SLAB);
      POLISHED_MUDSTONE = block(ThisIsStoneModBlocks.POLISHED_MUDSTONE);
      POLISHED_GREY_LIMESTONE = block(ThisIsStoneModBlocks.POLISHED_GREY_LIMESTONE);
      POLISHED_RHYOLITE = block(ThisIsStoneModBlocks.POLISHED_RHYOLITE);
      POLISHED_QUARTZITE = block(ThisIsStoneModBlocks.POLISHED_QUARTZITE);
      POLISHED_PERIDOTITE = block(ThisIsStoneModBlocks.POLISHED_PERIDOTITE);
      POLISHED_LIMESTONE = block(ThisIsStoneModBlocks.POLISHED_LIMESTONE);
      POLISHED_MARBLE_STAIRS = block(ThisIsStoneModBlocks.POLISHED_MARBLE_STAIRS);
      POLISHED_SOAPSTONE_STAIRS = block(ThisIsStoneModBlocks.POLISHED_SOAPSTONE_STAIRS);
      POLISHED_DOLOMITE_STAIRS = block(ThisIsStoneModBlocks.POLISHED_DOLOMITE_STAIRS);
      POLISHED_SERPENTINITE_STAIRS = block(ThisIsStoneModBlocks.POLISHED_SERPENTINITE_STAIRS);
      POLISHED_MUDSTONE_SLAB = block(ThisIsStoneModBlocks.POLISHED_MUDSTONE_SLAB);
      POLISHED_MUDSTONE_STAIRS = block(ThisIsStoneModBlocks.POLISHED_MUDSTONE_STAIRS);
      POLISHED_GREY_LIMESTONE_SLAB = block(ThisIsStoneModBlocks.POLISHED_GREY_LIMESTONE_SLAB);
      POLISHED_GREY_LIMESTONE_STAIRS = block(ThisIsStoneModBlocks.POLISHED_GREY_LIMESTONE_STAIRS);
      POLISHED_RHYOLITE_SLAB = block(ThisIsStoneModBlocks.POLISHED_RHYOLITE_SLAB);
      POLISHED_RHYOLITE_STAIRS = block(ThisIsStoneModBlocks.POLISHED_RHYOLITE_STAIRS);
      POLISHED_QUARTZITE_SLAB = block(ThisIsStoneModBlocks.POLISHED_QUARTZITE_SLAB);
      POLISHED_QUARTZITE_STAIRS = block(ThisIsStoneModBlocks.POLISHED_QUARTZITE_STAIRS);
      POLISHED_PERIDOTITE_SLAB = block(ThisIsStoneModBlocks.POLISHED_PERIDOTITE_SLAB);
      POLISHED_PERIDOTITE_STAIRS = block(ThisIsStoneModBlocks.POLISHED_PERIDOTITE_STAIRS);
      POLISHED_LIMESTONE_SLAB = block(ThisIsStoneModBlocks.POLISHED_LIMESTONE_SLAB);
      POLISHED_LIMESTONE_STAIRS = block(ThisIsStoneModBlocks.POLISHED_LIMESTONE_STAIRS);
      POLISHED_GNEISS_SLAB = block(ThisIsStoneModBlocks.POLISHED_GNEISS_SLAB);
      POLISHED_GNEISS_STAIRS = block(ThisIsStoneModBlocks.POLISHED_GNEISS_STAIRS);
      POLISHED_BLACK_MARBLE_SLAB = block(ThisIsStoneModBlocks.POLISHED_BLACK_MARBLE_SLAB);
      POLISHED_BLACK_MARBLE_STAIRS = block(ThisIsStoneModBlocks.POLISHED_BLACK_MARBLE_STAIRS);
      POLISHED_SCHIST = block(ThisIsStoneModBlocks.POLISHED_SCHIST);
      POLISHED_WHITE_LIMESTONE = block(ThisIsStoneModBlocks.POLISHED_WHITE_LIMESTONE);
      POLISHED_WHITE_LIMESTONE_SLAB = block(ThisIsStoneModBlocks.POLISHED_WHITE_LIMESTONE_SLAB);
      POLISHED_WHITE_LIMESTONE_STAIRS = block(ThisIsStoneModBlocks.POLISHED_WHITE_LIMESTONE_STAIRS);
   }
}
