package net.mcreator.whatisstone.init;

import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.ItemLike;
import net.minecraft.world.level.block.Block;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

public class WhatIsStoneModTabs {
   public static final DeferredRegister<CreativeModeTab> REGISTRY;
   public static final DeferredHolder<CreativeModeTab, CreativeModeTab> WHAT_IS_STONE;

   static {
      REGISTRY = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, "what_is_stone");
      WHAT_IS_STONE = REGISTRY.register("what_is_stone", () -> {
         return CreativeModeTab.builder().title(Component.translatable("item_group.what_is_stone.what_is_stone")).icon(() -> {
            return new ItemStack((ItemLike)WhatIsStoneModBlocks.GNEISS.get());
         }).displayItems((parameters, tabData) -> {
            tabData.accept(((Block)WhatIsStoneModBlocks.PUMICE_BRICKS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.PUMICE.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.GNEISS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_GNEISS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.MARBLE.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.CONGLOMERATE.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.DACITE.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.GABBRO.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.LIMESTONE.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.BRECCIA.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.WHITE_GRANITE.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.DOLOMITE.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.RHYOLITE.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.SHALE.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.PEGMATITE.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.SLATE.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.WHITE_LIMESTONE.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.SCHIST.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.SCORIA.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.BLACK_MARBLE.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.SERPENTINITE.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.ANTHRACITE.get()).asItem());
            tabData.accept((ItemLike)WhatIsStoneModItems.CHUNK_OF_ANTHRACITE.get());
            tabData.accept(((Block)WhatIsStoneModBlocks.SOAPSTONE.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.ARKOSIC_SANDSTONE.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.MUDSTONE.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.PERIDOTITE.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_BLACK_MARBLE.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.GREY_LIMESTONE.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_MARBLE.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_MARBLE_BRICKS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.MARBLE_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.MARBLE_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.BLACK_MARBLE_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.BLACK_MARBLE_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.PUMICE_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.PUMICE_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.LIMESTONE_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.LIMESTONE_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.LIMESTONE_BRICKS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.LIMESTONE_BRICK_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.LIMESTONE_BRICK_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.GNEISS_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.GNEISS_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.CONGLOMERATE_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.CONGLOMERATE_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.DACITE_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.DACITE_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.GABBRO_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.GABBRO_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.BRECCIA_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.BRECCIA_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.WHITE_GRANITE_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.WHITE_GRANITE_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.DOLOMITE_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.DOLOMITE_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.RHYOLITE_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.RHYOLITE_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.SHALE_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.SHALE_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.PEGMATITE_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.PEGMATITE_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.SLATE_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.SLATE_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.WHITE_LIMESTONE_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.WHITE_LIMESTONE_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.SCHIST_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.SCHIST_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.SCORIA_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.SCORIA_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.SERPENTINITE_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.SERPENTINITE_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.SOAPSTONE_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.SOAPSTONE_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.ARKOSIC_SANDSTONE_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.ARKOSIC_SANDSTONE_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.MUDSTONE_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.MUDSTONE_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.PERIDOTITE_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.PERIDOTITE_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.GREY_LIMESTONE_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.GREY_LIMESTONE_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.PUMICE_BRICK_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.PUMICE_BRICK_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_MARBLE_BRICK_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_MARBLE_BRICK_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.QUARTZITE.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.QUARTZITE_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.QUARTZITE_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.DACITE_BRICKS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.DACITE_BRICK_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.DACITE_BRICK_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_SOAPSTONE.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_SERPENTINITE.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_DOLOMITE.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_SOAPSTONE_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_DOLOMITE_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_SERPENTINITE_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_MARBLE_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_MUDSTONE.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_GREY_LIMESTONE.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_RHYOLITE.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_QUARTZITE.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_PERIDOTITE.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_LIMESTONE.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_MARBLE_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_SOAPSTONE_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_DOLOMITE_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_SERPENTINITE_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_MUDSTONE_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_MUDSTONE_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_GREY_LIMESTONE_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_GREY_LIMESTONE_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_RHYOLITE_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_RHYOLITE_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_QUARTZITE_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_QUARTZITE_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_PERIDOTITE_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_PERIDOTITE_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_LIMESTONE_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_LIMESTONE_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_GNEISS_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_GNEISS_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_BLACK_MARBLE_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_BLACK_MARBLE_STAIRS.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_SCHIST.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_WHITE_LIMESTONE.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_WHITE_LIMESTONE_SLAB.get()).asItem());
            tabData.accept(((Block)WhatIsStoneModBlocks.POLISHED_WHITE_LIMESTONE_STAIRS.get()).asItem());
         }).build();
      });
   }
}
